name: Gitea Actions Demo
run-name:   is testing out Gitea Actions ğŸš€
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a  event."
      - run: echo "ğŸ§ This job is now running on a  server hosted by Gitea!"
      - run: echo "ğŸ” The name of your branch is  and your repository is ${{ gitea.repository }}."
       
      - run: echo "ğŸ’¡ The  repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - run: echo "ğŸ This job's status is ${{ job.status }}."
